/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WorkoutLoggerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/i18n/en.ts
var en = {
  // Modal
  modalTitle: "\u{1F3CB}\uFE0F\u200D\u2642\uFE0F Log Workout Set",
  // Exercise
  exerciseLabel: "Exercise",
  exerciseDesc: "Select an existing exercise or type a new one to create it.",
  exercisePlaceholder: "e.g. Bench Press",
  // Target muscle
  targetMuscleLabel: "Target muscle",
  targetMuscleDesc: "Select the primary muscle group targeted.",
  targetMuscleOptions: ["Chest", "Back", "Shoulder", "Arms", "Abs", "Legs", "Cardio"],
  // Equipment
  equipmentLabel: "Equipment",
  equipmentDesc: "Select the equipment used.",
  equipmentTypeOptions: ["Barbell", "Dumbbell", "Machine", "Bodyweight", "Other"],
  // Log date
  logDateLabel: "Log date",
  logDateDesc: "Select the date for the workout log.",
  // Calorie inputs
  bodyWeightLabel: "Body weight (kg)",
  bodyWeightDesc: "Used for calorie calculation. Syncs with plugin settings.",
  bodyFatLabel: "Body fat percentage (%)",
  bodyFatDesc: "Current body fat %. Logged with the entry and syncs with plugin settings.",
  workoutDurationLabel: "Total exercise duration (min)",
  workoutDurationDesc: "Total time for this exercise. Divided equally across sets to calculate calories per set.",
  // Cardio
  cardioSectionLabel: "Cardio",
  cardioSpeedLabel: "Speed (km/h)",
  cardioInclineLabel: "Incline (%)",
  cardioDurationLabel: "Duration (min)",
  // Sets
  setWeight: (n) => `Set ${n} - Weight (kg/lbs)`,
  setReps: (n) => `Set ${n} - Reps`,
  setRpe: (n) => `Set ${n} - RPE`,
  addSet: "Add set",
  removeSet: "Remove set",
  // Buttons
  cancel: "Cancel",
  logSet: "Log set",
  // Notices
  noticeNoExercise: "\u26A0\uFE0F Please enter an exercise name!",
  noticeNoValidSet: "\u26A0\uFE0F Enter at least one valid set (weight and reps > 0)!",
  noticeNoDuration: "\u26A0\uFE0F Please enter a duration (minutes)!",
  noticeLoggedStrength: (summary, exercise) => `\u2705 Logged ${summary} for ${exercise}`,
  noticeLoggedCardio: (duration, calories, exercise) => `\u2705 Logged ${duration}min cardio (${calories} kcal) for ${exercise}`,
  noticeFailed: "\u274C Failed to log the set. Check console for details.",
  // Settings
  settingExerciseFolderName: "Exercise folder",
  settingExerciseFolderDesc: "The folder where your exercise notes are stored.",
  settingCalcCaloriesName: "Calculate calories burned",
  settingCalcCaloriesDesc: "Calculate calories burned based on METs, body weight, and workout duration.",
  settingBodyWeightName: "Default body weight (kg)",
  settingBodyWeightDesc: "Used for calorie calculation.",
  settingBodyFatName: "Default body fat percentage (%)",
  settingBodyFatDesc: "Logged alongside each workout entry to track body composition over time.",
  settingBodyMetricsNoteName: "Body metrics note",
  settingBodyMetricsNoteDesc: "Path to the note where daily body weight and body fat % are recorded (used when calorie calculation is enabled).",
  // Dashboard
  dashboardTitle: "Workout dashboard",
  dashboardRefresh: "\u21BB Refresh",
  periodWeek: "Week",
  periodMonth: "Month",
  periodYear: "Year",
  periodAll: "All time",
  sectionBodyMetrics: "Body metrics",
  bodyMetricsEmpty: "No data found. Enable calorie calculation and log your body weight.",
  chartWeight: "Body weight",
  chartBodyFat: "Body fat %",
  sectionCalories: "Calories burned",
  chartCaloriesLabel: "Calories burned (daily total)",
  sectionExercise: "Exercise log",
  exerciseEmpty: "No exercises found. Log a workout to get started.",
  exerciseDataEmpty: "No data for this exercise.",
  chartEstimated1RM: "Estimated 1RM",
  chartTotalVolume: "Total volume",
  chartNoData: "No data"
};
var en_default = en;

// src/i18n/ja.ts
var ja = {
  // Modal
  modalTitle: "\u{1F3CB}\uFE0F\u200D\u2642\uFE0F \u30C8\u30EC\u30FC\u30CB\u30F3\u30B0\u3092\u8A18\u9332",
  // Exercise
  exerciseLabel: "\u30A8\u30AF\u30B5\u30B5\u30A4\u30BA",
  exerciseDesc: "\u65E2\u5B58\u306E\u30A8\u30AF\u30B5\u30B5\u30A4\u30BA\u3092\u9078\u629E\u3059\u308B\u304B\u3001\u65B0\u3057\u3044\u540D\u524D\u3092\u5165\u529B\u3057\u3066\u4F5C\u6210\u3057\u307E\u3059\u3002",
  exercisePlaceholder: "\u4F8B: \u30D9\u30F3\u30C1\u30D7\u30EC\u30B9",
  // Target muscle
  targetMuscleLabel: "\u5BFE\u8C61\u7B4B\u8089",
  targetMuscleDesc: "\u4E3B\u306B\u935B\u3048\u308B\u7B4B\u8089\u30B0\u30EB\u30FC\u30D7\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
  targetMuscleOptions: ["\u80F8", "\u80CC\u4E2D", "\u80A9", "\u8155", "\u8179", "\u8DB3", "\u6709\u9178\u7D20"],
  // Equipment
  equipmentLabel: "\u5668\u5177",
  equipmentDesc: "\u4F7F\u7528\u3059\u308B\u5668\u5177\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
  equipmentTypeOptions: ["\u30D0\u30FC\u30D9\u30EB", "\u30C0\u30F3\u30D9\u30EB", "\u30DE\u30B7\u30F3", "\u81EA\u91CD", "\u305D\u306E\u4ED6"],
  // Log date
  logDateLabel: "\u8A18\u9332\u65E5",
  logDateDesc: "\u30C8\u30EC\u30FC\u30CB\u30F3\u30B0\u30ED\u30B0\u306E\u65E5\u4ED8\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
  // Calorie inputs
  bodyWeightLabel: "\u4F53\u91CD (kg)",
  bodyWeightDesc: "\u30AB\u30ED\u30EA\u30FC\u8A08\u7B97\u306B\u4F7F\u7528\u3057\u307E\u3059\u3002\u30D7\u30E9\u30B0\u30A4\u30F3\u8A2D\u5B9A\u3068\u540C\u671F\u3055\u308C\u307E\u3059\u3002",
  bodyFatLabel: "\u4F53\u8102\u80AA\u7387 (%)",
  bodyFatDesc: "\u73FE\u5728\u306E\u4F53\u8102\u80AA\u7387\u3002\u30A8\u30F3\u30C8\u30EA\u3068\u4E00\u7DD2\u306B\u8A18\u9332\u3055\u308C\u3001\u30D7\u30E9\u30B0\u30A4\u30F3\u8A2D\u5B9A\u3068\u540C\u671F\u3055\u308C\u307E\u3059\u3002",
  workoutDurationLabel: "\u30A8\u30AF\u30B5\u30B5\u30A4\u30BA\u5168\u4F53\u306E\u6642\u9593 (\u5206)",
  workoutDurationDesc: "\u3053\u306E\u30A8\u30AF\u30B5\u30B5\u30A4\u30BA\u306B\u304B\u3051\u305F\u5408\u8A08\u6642\u9593\u3002\u30BB\u30C3\u30C8\u6570\u3067\u7B49\u5206\u3057\u3066\u5404\u30BB\u30C3\u30C8\u306E\u6D88\u8CBB\u30AB\u30ED\u30EA\u30FC\u3092\u8A08\u7B97\u3057\u307E\u3059\u3002",
  // Cardio
  cardioSectionLabel: "\u6709\u9178\u7D20\u904B\u52D5",
  cardioSpeedLabel: "\u901F\u5EA6 (km/h)",
  cardioInclineLabel: "\u50BE\u659C (%)",
  cardioDurationLabel: "\u6642\u9593 (\u5206)",
  // Sets
  setWeight: (n) => `\u30BB\u30C3\u30C8 ${n} - \u91CD\u91CF (kg/lbs)`,
  setReps: (n) => `\u30BB\u30C3\u30C8 ${n} - \u56DE\u6570`,
  setRpe: (n) => `\u30BB\u30C3\u30C8 ${n} - RPE`,
  addSet: "\u30BB\u30C3\u30C8\u3092\u8FFD\u52A0",
  removeSet: "\u30BB\u30C3\u30C8\u3092\u524A\u9664",
  // Buttons
  cancel: "\u30AD\u30E3\u30F3\u30BB\u30EB",
  logSet: "\u8A18\u9332\u3059\u308B",
  // Notices
  noticeNoExercise: "\u26A0\uFE0F \u30A8\u30AF\u30B5\u30B5\u30A4\u30BA\u540D\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\uFF01",
  noticeNoValidSet: "\u26A0\uFE0F \u6709\u52B9\u306A\u30BB\u30C3\u30C8\u3092\u5C11\u306A\u304F\u3068\u30821\u3064\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044 (\u91CD\u91CF\u3068\u56DE\u6570\u304C0\u3088\u308A\u5927\u304D\u3044)\uFF01",
  noticeNoDuration: "\u26A0\uFE0F \u6642\u9593\uFF08\u5206\uFF09\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\uFF01",
  noticeLoggedStrength: (summary, exercise) => `\u2705 ${exercise} \u3092\u8A18\u9332\u3057\u307E\u3057\u305F: ${summary}`,
  noticeLoggedCardio: (duration, calories, exercise) => `\u2705 ${exercise} \u306E\u6709\u9178\u7D20\u904B\u52D5\u3092\u8A18\u9332\u3057\u307E\u3057\u305F: ${duration}\u5206 (${calories} kcal)`,
  noticeFailed: "\u274C \u8A18\u9332\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002\u30B3\u30F3\u30BD\u30FC\u30EB\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
  // Settings
  settingExerciseFolderName: "\u30A8\u30AF\u30B5\u30B5\u30A4\u30BA\u30D5\u30A9\u30EB\u30C0",
  settingExerciseFolderDesc: "\u30A8\u30AF\u30B5\u30B5\u30A4\u30BA\u30CE\u30FC\u30C8\u3092\u4FDD\u5B58\u3059\u308B\u30D5\u30A9\u30EB\u30C0\u306E\u30D1\u30B9\u3092\u6307\u5B9A\u3057\u307E\u3059\u3002",
  settingCalcCaloriesName: "\u6D88\u8CBB\u30AB\u30ED\u30EA\u30FC\u3092\u8A08\u7B97\u3059\u308B",
  settingCalcCaloriesDesc: "METs\u30FB\u4F53\u91CD\u30FB\u904B\u52D5\u6642\u9593\u3092\u3082\u3068\u306B\u6D88\u8CBB\u30AB\u30ED\u30EA\u30FC\u3092\u8A08\u7B97\u3057\u307E\u3059\u3002",
  settingBodyWeightName: "\u30C7\u30D5\u30A9\u30EB\u30C8\u4F53\u91CD (kg)",
  settingBodyWeightDesc: "\u30AB\u30ED\u30EA\u30FC\u8A08\u7B97\u306B\u4F7F\u7528\u3057\u307E\u3059\u3002",
  settingBodyFatName: "\u30C7\u30D5\u30A9\u30EB\u30C8\u4F53\u8102\u80AA\u7387 (%)",
  settingBodyFatDesc: "\u5404\u30C8\u30EC\u30FC\u30CB\u30F3\u30B0\u30A8\u30F3\u30C8\u30EA\u3068\u3068\u3082\u306B\u8A18\u9332\u3057\u3001\u4F53\u7D44\u6210\u306E\u5909\u5316\u3092\u8FFD\u8DE1\u3057\u307E\u3059\u3002",
  settingBodyMetricsNoteName: "\u8EAB\u4F53\u8A18\u9332\u30CE\u30FC\u30C8",
  settingBodyMetricsNoteDesc: "\u4F53\u91CD\u30FB\u4F53\u8102\u80AA\u7387\u3092\u65E5\u6B21\u8A18\u9332\u3059\u308B\u30CE\u30FC\u30C8\u306E\u30D1\u30B9\uFF08\u30AB\u30ED\u30EA\u30FC\u8A08\u7B97\u30AA\u30F3\u6642\u306B\u4F7F\u7528\uFF09\u3002",
  // Dashboard
  dashboardTitle: "\u30EF\u30FC\u30AF\u30A2\u30A6\u30C8\u30C0\u30C3\u30B7\u30E5\u30DC\u30FC\u30C9",
  dashboardRefresh: "\u21BB \u66F4\u65B0",
  periodWeek: "\u9031\u9593",
  periodMonth: "\u6708\u9593",
  periodYear: "\u5E74\u9593",
  periodAll: "\u5168\u671F\u9593",
  sectionBodyMetrics: "\u8EAB\u4F53\u8A18\u9332",
  bodyMetricsEmpty: "\u30C7\u30FC\u30BF\u304C\u3042\u308A\u307E\u305B\u3093\u3002\u30AB\u30ED\u30EA\u30FC\u8A08\u7B97\u3092\u30AA\u30F3\u306B\u3057\u3066\u4F53\u91CD\u3092\u8A18\u9332\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
  chartWeight: "\u4F53\u91CD",
  chartBodyFat: "\u4F53\u8102\u80AA\u7387",
  sectionCalories: "\u6D88\u8CBB\u30AB\u30ED\u30EA\u30FC",
  chartCaloriesLabel: "\u6D88\u8CBB\u30AB\u30ED\u30EA\u30FC\uFF08\u65E5\u6B21\u5408\u8A08\uFF09",
  sectionExercise: "\u30A8\u30AF\u30B5\u30B5\u30A4\u30BA\u8A18\u9332",
  exerciseEmpty: "\u30C7\u30FC\u30BF\u304C\u3042\u308A\u307E\u305B\u3093\u3002\u30C8\u30EC\u30FC\u30CB\u30F3\u30B0\u3092\u8A18\u9332\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
  exerciseDataEmpty: "\u3053\u306E\u30A8\u30AF\u30B5\u30B5\u30A4\u30BA\u306E\u30C7\u30FC\u30BF\u304C\u3042\u308A\u307E\u305B\u3093\u3002",
  chartEstimated1RM: "\u63A8\u5B9A1RM",
  chartTotalVolume: "\u7DCF\u30DC\u30EA\u30E5\u30FC\u30E0",
  chartNoData: "\u30C7\u30FC\u30BF\u306A\u3057"
};
var ja_default = ja;

// src/i18n/zh.ts
var zh = {
  // Modal
  modalTitle: "\u{1F3CB}\uFE0F\u200D\u2642\uFE0F \u8BB0\u5F55\u8BAD\u7EC3\u7EC4",
  // Exercise
  exerciseLabel: "\u8BAD\u7EC3\u52A8\u4F5C",
  exerciseDesc: "\u9009\u62E9\u5DF2\u6709\u52A8\u4F5C\uFF0C\u6216\u8F93\u5165\u65B0\u540D\u79F0\u4EE5\u521B\u5EFA\u3002",
  exercisePlaceholder: "\u4F8B\uFF1A\u5367\u63A8",
  // Target muscle
  targetMuscleLabel: "\u76EE\u6807\u808C\u7FA4",
  targetMuscleDesc: "\u9009\u62E9\u672C\u6B21\u8BAD\u7EC3\u7684\u4E3B\u8981\u808C\u7FA4\u3002",
  targetMuscleOptions: ["\u80F8", "\u80CC", "\u80A9", "\u624B\u81C2", "\u8179", "\u817F", "\u6709\u6C27"],
  // Equipment
  equipmentLabel: "\u5668\u68B0",
  equipmentDesc: "\u9009\u62E9\u4F7F\u7528\u7684\u5668\u68B0\u3002",
  equipmentTypeOptions: ["\u6760\u94C3", "\u54D1\u94C3", "\u5668\u68B0", "\u81EA\u91CD", "\u5176\u4ED6"],
  // Log date
  logDateLabel: "\u8BB0\u5F55\u65E5\u671F",
  logDateDesc: "\u9009\u62E9\u672C\u6B21\u8BAD\u7EC3\u7684\u65E5\u671F\u3002",
  // Calorie inputs
  bodyWeightLabel: "\u4F53\u91CD (kg)",
  bodyWeightDesc: "\u7528\u4E8E\u5361\u8DEF\u91CC\u8BA1\u7B97\uFF0C\u4E0E\u63D2\u4EF6\u8BBE\u7F6E\u540C\u6B65\u3002",
  bodyFatLabel: "\u4F53\u8102\u7387 (%)",
  bodyFatDesc: "\u5F53\u524D\u4F53\u8102\u7387\uFF0C\u968F\u8BB0\u5F55\u4FDD\u5B58\u5E76\u4E0E\u63D2\u4EF6\u8BBE\u7F6E\u540C\u6B65\u3002",
  workoutDurationLabel: "\u8BAD\u7EC3\u603B\u65F6\u957F (\u5206\u949F)",
  workoutDurationDesc: "\u672C\u6B21\u8BAD\u7EC3\u7684\u603B\u65F6\u957F\uFF0C\u5C06\u5E73\u5747\u5206\u914D\u5230\u5404\u7EC4\u4EE5\u8BA1\u7B97\u6BCF\u7EC4\u6D88\u8017\u5361\u8DEF\u91CC\u3002",
  // Cardio
  cardioSectionLabel: "\u6709\u6C27\u8FD0\u52A8",
  cardioSpeedLabel: "\u901F\u5EA6 (km/h)",
  cardioInclineLabel: "\u5761\u5EA6 (%)",
  cardioDurationLabel: "\u65F6\u957F (\u5206\u949F)",
  // Sets
  setWeight: (n) => `\u7B2C ${n} \u7EC4 - \u91CD\u91CF (kg/lbs)`,
  setReps: (n) => `\u7B2C ${n} \u7EC4 - \u6B21\u6570`,
  setRpe: (n) => `\u7B2C ${n} \u7EC4 - RPE`,
  addSet: "\u6DFB\u52A0\u7EC4",
  removeSet: "\u5220\u9664\u7EC4",
  // Buttons
  cancel: "\u53D6\u6D88",
  logSet: "\u8BB0\u5F55",
  // Notices
  noticeNoExercise: "\u26A0\uFE0F \u8BF7\u8F93\u5165\u8BAD\u7EC3\u52A8\u4F5C\u540D\u79F0\uFF01",
  noticeNoValidSet: "\u26A0\uFE0F \u8BF7\u81F3\u5C11\u8F93\u5165\u4E00\u7EC4\u6709\u6548\u6570\u636E\uFF08\u91CD\u91CF\u548C\u6B21\u6570\u5747\u5927\u4E8E0\uFF09\uFF01",
  noticeNoDuration: "\u26A0\uFE0F \u8BF7\u8F93\u5165\u65F6\u957F\uFF08\u5206\u949F\uFF09\uFF01",
  noticeLoggedStrength: (summary, exercise) => `\u2705 \u5DF2\u8BB0\u5F55 ${exercise}\uFF1A${summary}`,
  noticeLoggedCardio: (duration, calories, exercise) => `\u2705 \u5DF2\u8BB0\u5F55 ${exercise} \u7684\u6709\u6C27\u8FD0\u52A8\uFF1A${duration}\u5206\u949F (${calories} kcal)`,
  noticeFailed: "\u274C \u8BB0\u5F55\u5931\u8D25\uFF0C\u8BF7\u67E5\u770B\u63A7\u5236\u53F0\u3002",
  // Settings
  settingExerciseFolderName: "\u8BAD\u7EC3\u6587\u4EF6\u5939",
  settingExerciseFolderDesc: "\u5B58\u50A8\u8BAD\u7EC3\u7B14\u8BB0\u7684\u6587\u4EF6\u5939\u8DEF\u5F84\u3002",
  settingCalcCaloriesName: "\u8BA1\u7B97\u6D88\u8017\u5361\u8DEF\u91CC",
  settingCalcCaloriesDesc: "\u57FA\u4E8EMETs\u3001\u4F53\u91CD\u548C\u8BAD\u7EC3\u65F6\u957F\u8BA1\u7B97\u6D88\u8017\u5361\u8DEF\u91CC\u3002",
  settingBodyWeightName: "\u9ED8\u8BA4\u4F53\u91CD (kg)",
  settingBodyWeightDesc: "\u7528\u4E8E\u5361\u8DEF\u91CC\u8BA1\u7B97\u3002",
  settingBodyFatName: "\u9ED8\u8BA4\u4F53\u8102\u7387 (%)",
  settingBodyFatDesc: "\u968F\u6BCF\u6761\u8BAD\u7EC3\u8BB0\u5F55\u4FDD\u5B58\uFF0C\u7528\u4E8E\u8FFD\u8E2A\u4F53\u6210\u5206\u53D8\u5316\u3002",
  settingBodyMetricsNoteName: "\u8EAB\u4F53\u6570\u636E\u7B14\u8BB0",
  settingBodyMetricsNoteDesc: "\u6BCF\u65E5\u8BB0\u5F55\u4F53\u91CD\u548C\u4F53\u8102\u7387\u7684\u7B14\u8BB0\u8DEF\u5F84\uFF08\u542F\u7528\u5361\u8DEF\u91CC\u8BA1\u7B97\u65F6\u4F7F\u7528\uFF09\u3002",
  // Dashboard
  dashboardTitle: "\u8BAD\u7EC3\u4EEA\u8868\u76D8",
  dashboardRefresh: "\u21BB \u5237\u65B0",
  periodWeek: "\u672C\u5468",
  periodMonth: "\u672C\u6708",
  periodYear: "\u672C\u5E74",
  periodAll: "\u5168\u90E8",
  sectionBodyMetrics: "\u8EAB\u4F53\u6570\u636E",
  bodyMetricsEmpty: "\u6682\u65E0\u6570\u636E\u3002\u8BF7\u5F00\u542F\u5361\u8DEF\u91CC\u8BA1\u7B97\u5E76\u8BB0\u5F55\u4F53\u91CD\u3002",
  chartWeight: "\u4F53\u91CD",
  chartBodyFat: "\u4F53\u8102\u7387",
  sectionCalories: "\u6D88\u8017\u5361\u8DEF\u91CC",
  chartCaloriesLabel: "\u6D88\u8017\u5361\u8DEF\u91CC\uFF08\u6BCF\u65E5\u5408\u8BA1\uFF09",
  sectionExercise: "\u8BAD\u7EC3\u8BB0\u5F55",
  exerciseEmpty: "\u6682\u65E0\u6570\u636E\u3002\u8BF7\u8BB0\u5F55\u4E00\u6B21\u8BAD\u7EC3\u4EE5\u5F00\u59CB\u3002",
  exerciseDataEmpty: "\u8BE5\u52A8\u4F5C\u6682\u65E0\u6570\u636E\u3002",
  chartEstimated1RM: "\u9884\u4F301RM",
  chartTotalVolume: "\u603B\u8BAD\u7EC3\u91CF",
  chartNoData: "\u6682\u65E0\u6570\u636E"
};
var zh_default = zh;

// src/i18n/ko.ts
var ko = {
  // Modal
  modalTitle: "\u{1F3CB}\uFE0F\u200D\u2642\uFE0F \uC6B4\uB3D9 \uC138\uD2B8 \uAE30\uB85D",
  // Exercise
  exerciseLabel: "\uC6B4\uB3D9",
  exerciseDesc: "\uAE30\uC874 \uC6B4\uB3D9\uC744 \uC120\uD0DD\uD558\uAC70\uB098 \uC0C8 \uC774\uB984\uC744 \uC785\uB825\uD558\uC5EC \uC0DD\uC131\uD558\uC138\uC694.",
  exercisePlaceholder: "\uC608: \uBCA4\uCE58 \uD504\uB808\uC2A4",
  // Target muscle
  targetMuscleLabel: "\uBAA9\uD45C \uADFC\uC721",
  targetMuscleDesc: "\uC8FC\uC694 \uBAA9\uD45C \uADFC\uC721 \uADF8\uB8F9\uC744 \uC120\uD0DD\uD558\uC138\uC694.",
  targetMuscleOptions: ["\uAC00\uC2B4", "\uB4F1", "\uC5B4\uAE68", "\uD314", "\uBCF5\uADFC", "\uD558\uCCB4", "\uC720\uC0B0\uC18C"],
  // Equipment
  equipmentLabel: "\uAE30\uAD6C",
  equipmentDesc: "\uC0AC\uC6A9\uD558\uB294 \uAE30\uAD6C\uB97C \uC120\uD0DD\uD558\uC138\uC694.",
  equipmentTypeOptions: ["\uBC14\uBCA8", "\uB364\uBCA8", "\uBA38\uC2E0", "\uB9E8\uBAB8", "\uAE30\uD0C0"],
  // Log date
  logDateLabel: "\uAE30\uB85D \uB0A0\uC9DC",
  logDateDesc: "\uC6B4\uB3D9 \uAE30\uB85D \uB0A0\uC9DC\uB97C \uC120\uD0DD\uD558\uC138\uC694.",
  // Calorie inputs
  bodyWeightLabel: "\uCCB4\uC911 (kg)",
  bodyWeightDesc: "\uCE7C\uB85C\uB9AC \uACC4\uC0B0\uC5D0 \uC0AC\uC6A9\uB429\uB2C8\uB2E4. \uD50C\uB7EC\uADF8\uC778 \uC124\uC815\uACFC \uB3D9\uAE30\uD654\uB429\uB2C8\uB2E4.",
  bodyFatLabel: "\uCCB4\uC9C0\uBC29\uB960 (%)",
  bodyFatDesc: "\uD604\uC7AC \uCCB4\uC9C0\uBC29\uB960. \uAE30\uB85D\uACFC \uD568\uAED8 \uC800\uC7A5\uB418\uBA70 \uD50C\uB7EC\uADF8\uC778 \uC124\uC815\uACFC \uB3D9\uAE30\uD654\uB429\uB2C8\uB2E4.",
  workoutDurationLabel: "\uC804\uCCB4 \uC6B4\uB3D9 \uC2DC\uAC04 (\uBD84)",
  workoutDurationDesc: "\uC774 \uC6B4\uB3D9\uC5D0 \uC18C\uC694\uB41C \uCD1D \uC2DC\uAC04. \uC138\uD2B8 \uC218\uB85C \uB098\uB204\uC5B4 \uC138\uD2B8\uBCC4 \uC18C\uBAA8 \uCE7C\uB85C\uB9AC\uB97C \uACC4\uC0B0\uD569\uB2C8\uB2E4.",
  // Cardio
  cardioSectionLabel: "\uC720\uC0B0\uC18C \uC6B4\uB3D9",
  cardioSpeedLabel: "\uC18D\uB3C4 (km/h)",
  cardioInclineLabel: "\uACBD\uC0AC (%)",
  cardioDurationLabel: "\uC2DC\uAC04 (\uBD84)",
  // Sets
  setWeight: (n) => `\uC138\uD2B8 ${n} - \uBB34\uAC8C (kg/lbs)`,
  setReps: (n) => `\uC138\uD2B8 ${n} - \uD69F\uC218`,
  setRpe: (n) => `\uC138\uD2B8 ${n} - RPE`,
  addSet: "\uC138\uD2B8 \uCD94\uAC00",
  removeSet: "\uC138\uD2B8 \uC0AD\uC81C",
  // Buttons
  cancel: "\uCDE8\uC18C",
  logSet: "\uAE30\uB85D",
  // Notices
  noticeNoExercise: "\u26A0\uFE0F \uC6B4\uB3D9 \uC774\uB984\uC744 \uC785\uB825\uD558\uC138\uC694!",
  noticeNoValidSet: "\u26A0\uFE0F \uC720\uD6A8\uD55C \uC138\uD2B8\uB97C \uCD5C\uC18C \uD558\uB098 \uC785\uB825\uD558\uC138\uC694 (\uBB34\uAC8C\uC640 \uD69F\uC218 \uBAA8\uB450 0\uBCF4\uB2E4 \uCEE4\uC57C \uD569\uB2C8\uB2E4)!",
  noticeNoDuration: "\u26A0\uFE0F \uC2DC\uAC04(\uBD84)\uC744 \uC785\uB825\uD558\uC138\uC694!",
  noticeLoggedStrength: (summary, exercise) => `\u2705 ${exercise} \uAE30\uB85D \uC644\uB8CC: ${summary}`,
  noticeLoggedCardio: (duration, calories, exercise) => `\u2705 ${exercise} \uC720\uC0B0\uC18C \uC6B4\uB3D9 \uAE30\uB85D \uC644\uB8CC: ${duration}\uBD84 (${calories} kcal)`,
  noticeFailed: "\u274C \uAE30\uB85D\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4. \uCF58\uC194\uC744 \uD655\uC778\uD558\uC138\uC694.",
  // Settings
  settingExerciseFolderName: "\uC6B4\uB3D9 \uD3F4\uB354",
  settingExerciseFolderDesc: "\uC6B4\uB3D9 \uB178\uD2B8\uAC00 \uC800\uC7A5\uB41C \uD3F4\uB354 \uACBD\uB85C\uB97C \uC9C0\uC815\uD558\uC138\uC694.",
  settingCalcCaloriesName: "\uC18C\uBAA8 \uCE7C\uB85C\uB9AC \uACC4\uC0B0",
  settingCalcCaloriesDesc: "METs, \uCCB4\uC911, \uC6B4\uB3D9 \uC2DC\uAC04\uC744 \uAE30\uBC18\uC73C\uB85C \uC18C\uBAA8 \uCE7C\uB85C\uB9AC\uB97C \uACC4\uC0B0\uD569\uB2C8\uB2E4.",
  settingBodyWeightName: "\uAE30\uBCF8 \uCCB4\uC911 (kg)",
  settingBodyWeightDesc: "\uCE7C\uB85C\uB9AC \uACC4\uC0B0\uC5D0 \uC0AC\uC6A9\uB429\uB2C8\uB2E4.",
  settingBodyFatName: "\uAE30\uBCF8 \uCCB4\uC9C0\uBC29\uB960 (%)",
  settingBodyFatDesc: "\uAC01 \uC6B4\uB3D9 \uAE30\uB85D\uACFC \uD568\uAED8 \uC800\uC7A5\uD558\uC5EC \uCCB4\uC131\uBD84 \uBCC0\uD654\uB97C \uCD94\uC801\uD569\uB2C8\uB2E4.",
  settingBodyMetricsNoteName: "\uC2E0\uCCB4 \uAE30\uB85D \uB178\uD2B8",
  settingBodyMetricsNoteDesc: "\uCCB4\uC911\uACFC \uCCB4\uC9C0\uBC29\uB960\uC744 \uC77C\uBCC4\uB85C \uAE30\uB85D\uD558\uB294 \uB178\uD2B8 \uACBD\uB85C (\uCE7C\uB85C\uB9AC \uACC4\uC0B0 \uD65C\uC131\uD654 \uC2DC \uC0AC\uC6A9).",
  // Dashboard
  dashboardTitle: "\uC6B4\uB3D9 \uB300\uC2DC\uBCF4\uB4DC",
  dashboardRefresh: "\u21BB \uC0C8\uB85C\uACE0\uCE68",
  periodWeek: "\uC8FC\uAC04",
  periodMonth: "\uC6D4\uAC04",
  periodYear: "\uC5F0\uAC04",
  periodAll: "\uC804\uCCB4",
  sectionBodyMetrics: "\uC2E0\uCCB4 \uAE30\uB85D",
  bodyMetricsEmpty: "\uB370\uC774\uD130\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4. \uCE7C\uB85C\uB9AC \uACC4\uC0B0\uC744 \uD65C\uC131\uD654\uD558\uACE0 \uCCB4\uC911\uC744 \uAE30\uB85D\uD558\uC138\uC694.",
  chartWeight: "\uCCB4\uC911",
  chartBodyFat: "\uCCB4\uC9C0\uBC29\uB960",
  sectionCalories: "\uC18C\uBAA8 \uCE7C\uB85C\uB9AC",
  chartCaloriesLabel: "\uC18C\uBAA8 \uCE7C\uB85C\uB9AC (\uC77C\uBCC4 \uD569\uACC4)",
  sectionExercise: "\uC6B4\uB3D9 \uAE30\uB85D",
  exerciseEmpty: "\uB370\uC774\uD130\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4. \uC6B4\uB3D9\uC744 \uAE30\uB85D\uD558\uC138\uC694.",
  exerciseDataEmpty: "\uC774 \uC6B4\uB3D9\uC758 \uB370\uC774\uD130\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.",
  chartEstimated1RM: "\uCD94\uC815 1RM",
  chartTotalVolume: "\uCD1D \uBCFC\uB968",
  chartNoData: "\uB370\uC774\uD130 \uC5C6\uC74C"
};
var ko_default = ko;

// src/i18n/index.ts
var locales = { en: en_default, ja: ja_default, zh: zh_default, ko: ko_default };
function detect() {
  var _a;
  const lang = (_a = window.localStorage.getItem("language")) != null ? _a : "en";
  if (lang.startsWith("zh"))
    return "zh";
  return locales[lang] ? lang : "en";
}
function t() {
  return locales[detect()];
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  exerciseFolder: "Gym/Exercises",
  calculateCalories: false,
  bodyWeight: 60,
  bodyFatPercentage: 0,
  bodyMetricsNote: "Gym/BodyMetrics"
};
var WorkoutLoggerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /** Attach a <datalist> to an input element with the given options. */
  attachDatalist(inputEl, listId, options) {
    let datalist = this.containerEl.querySelector(
      `#${listId}`
    );
    if (!datalist) {
      datalist = this.containerEl.createEl("datalist", {
        attr: { id: listId }
      });
    } else {
      datalist.empty();
    }
    for (const opt of options) {
      datalist.createEl("option", { value: opt });
    }
    inputEl.setAttribute("list", listId);
  }
  /** All folder paths in the vault, sorted. */
  folderOptions() {
    return this.app.vault.getAllFolders().map((f) => f.path).filter((p) => p !== "/").sort();
  }
  /** All markdown file paths in the vault (without .md), sorted. */
  noteOptions() {
    return this.app.vault.getMarkdownFiles().map((f) => f.path.replace(/\.md$/, "")).sort();
  }
  display() {
    const { containerEl } = this;
    const i18n = t();
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName(i18n.settingExerciseFolderName).setDesc(i18n.settingExerciseFolderDesc).addText((text) => {
      this.attachDatalist(text.inputEl, "wl-folder-list", this.folderOptions());
      text.setPlaceholder("e.g., Gym/Exercises").setValue(this.plugin.settings.exerciseFolder).onChange(async (value) => {
        this.plugin.settings.exerciseFolder = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName(i18n.settingCalcCaloriesName).setDesc(i18n.settingCalcCaloriesDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.calculateCalories).onChange(async (value) => {
        this.plugin.settings.calculateCalories = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.calculateCalories) {
      new import_obsidian.Setting(containerEl).setName(i18n.settingBodyWeightName).setDesc(i18n.settingBodyWeightDesc).addText(
        (text) => text.setPlaceholder("e.g., 60").setValue(this.plugin.settings.bodyWeight.toString()).onChange(async (value) => {
          this.plugin.settings.bodyWeight = parseFloat(value) || 60;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName(i18n.settingBodyFatName).setDesc(i18n.settingBodyFatDesc).addText(
        (text) => text.setPlaceholder("e.g., 20").setValue(this.plugin.settings.bodyFatPercentage.toString()).onChange(async (value) => {
          this.plugin.settings.bodyFatPercentage = parseFloat(value) || 0;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName(i18n.settingBodyMetricsNoteName).setDesc(i18n.settingBodyMetricsNoteDesc).addText((text) => {
        this.attachDatalist(text.inputEl, "wl-note-list", this.noteOptions());
        text.setPlaceholder("e.g., Gym/BodyMetrics").setValue(this.plugin.settings.bodyMetricsNote).onChange(async (value) => {
          this.plugin.settings.bodyMetricsNote = value;
          await this.plugin.saveSettings();
        });
      });
    }
  }
};

// src/LoggerModal.ts
var import_obsidian3 = require("obsidian");

// src/file.ts
var import_obsidian2 = require("obsidian");

// src/utils.ts
function calculateVolume(weight, reps) {
  return Math.round(weight * reps);
}
function calculate1RM(weight, reps) {
  if (reps === 0)
    return 0;
  if (reps === 1)
    return weight;
  const oneRM = weight * (1 + reps / 30);
  return Math.round(oneRM * 10) / 10;
}
var EQUIPMENT_METS = {
  Barbell: 6,
  Dumbbell: 6,
  Machine: 5,
  Bodyweight: 3.8,
  Other: 5
};
function calculateCalories(mets, weight, duration) {
  return Math.round(mets * weight * duration * 1.05);
}
var calculateWalkingCalorie = (weight, kph, inclinePercent, minutes) => {
  const v = kph / 0.06;
  const g = inclinePercent / 100;
  const vo2 = 0.1 * v + 1.8 * v * g + 3.5;
  return vo2 * weight / 1e3 * 5 * minutes;
};

// src/file.ts
async function ensureFolderExists(app, folderPath) {
  const normalizedPath = (0, import_obsidian2.normalizePath)(folderPath);
  const folders = normalizedPath.split("/");
  let currentPath = "";
  for (const folder of folders) {
    if (folder === "")
      continue;
    currentPath = currentPath === "" ? folder : `${currentPath}/${folder}`;
    const abstractFile = app.vault.getAbstractFileByPath(currentPath);
    if (!abstractFile) {
      await app.vault.createFolder(currentPath);
    } else if (!(abstractFile instanceof import_obsidian2.TFolder)) {
      throw new Error(`${currentPath} is not a folder.`);
    }
  }
}
async function getOrCreateExerciseNote(app, exerciseFolder, exerciseName, targetMuscle = "", equipment = "") {
  const fileName = exerciseName.endsWith(".md") ? exerciseName : `${exerciseName}.md`;
  const filePath = (0, import_obsidian2.normalizePath)(`${exerciseFolder}/${fileName}`);
  let file = app.vault.getAbstractFileByPath(filePath);
  if (file instanceof import_obsidian2.TFile) {
    return file;
  }
  await ensureFolderExists(app, exerciseFolder);
  const template = `---
target_muscle: ${targetMuscle ? `["${targetMuscle}"]` : "[]"}
equipment: "${equipment}"
is_assisted: false
---

# ${exerciseName.replace(".md", "")}

## Log
`;
  file = await app.vault.create(filePath, template);
  if (!(file instanceof import_obsidian2.TFile)) {
    throw new Error(`Failed to create file: ${filePath}`);
  }
  return file;
}
async function appendBodyMetrics(app, notePath, date, bodyWeight, bodyFatPercentage) {
  const normalizedPath = (0, import_obsidian2.normalizePath)(
    notePath.endsWith(".md") ? notePath : `${notePath}.md`
  );
  const parts = normalizedPath.split("/");
  if (parts.length > 1) {
    const folderPath = parts.slice(0, -1).join("/");
    await ensureFolderExists(app, folderPath);
  }
  let file = app.vault.getAbstractFileByPath(normalizedPath);
  if (!(file instanceof import_obsidian2.TFile)) {
    const template = `# Body Metrics

## Log
`;
    file = await app.vault.create(normalizedPath, template);
  }
  if (!(file instanceof import_obsidian2.TFile)) {
    throw new Error(`Failed to get or create file: ${normalizedPath}`);
  }
  let alreadyLogged = false;
  await app.vault.process(file, (data) => {
    if (data.includes(`[date:: ${date}]`)) {
      alreadyLogged = true;
      return data;
    }
    const line = `- [date:: ${date}] | [body_weight:: ${bodyWeight}] | [body_fat_percentage:: ${bodyFatPercentage}]`;
    const separator = data.endsWith("\n") ? "" : "\n";
    return `${data}${separator}${line}
`;
  });
  return !alreadyLogged;
}
async function appendLog(app, file, sets, logDate, extra) {
  const logLines = sets.map((set) => {
    const volume = calculateVolume(set.weight, set.reps);
    const oneRM = calculate1RM(set.weight, set.reps);
    let line = `- [date:: ${logDate}] | [weight:: ${set.weight}] kg x [reps:: ${set.reps}] | [volume:: ${volume}] | [rm:: ${oneRM}]`;
    if (set.rpe !== null) {
      line += ` | [rpe:: ${set.rpe}]`;
    }
    if (extra && extra.duration > 0) {
      line += ` | [duration:: ${extra.duration}] | [calories:: ${extra.calories}]`;
    }
    return line;
  }).join("\n");
  await app.vault.process(file, (data) => {
    const separator = data.endsWith("\n") ? "" : "\n";
    return `${data}${separator}${logLines}
`;
  });
}
async function appendCardioLog(app, file, logDate, speed, incline, duration, calories) {
  const line = `- [date:: ${logDate}] | [speed:: ${speed}] | [incline:: ${incline}] | [duration:: ${duration}] | [calories:: ${calories}]`;
  await app.vault.process(file, (data) => {
    const separator = data.endsWith("\n") ? "" : "\n";
    return `${data}${separator}${line}
`;
  });
}

// src/LoggerModal.ts
var TARGET_MUSCLES = ["Chest", "Back", "Shoulder", "Arms", "Abs", "Legs", "Cardio"];
var EQUIPMENT_TYPES = [
  "Barbell",
  "Dumbbell",
  "Machine",
  "Bodyweight",
  "Other"
];
var LoggerModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.exerciseName = "";
    this.sets = [];
    this.logDate = window.moment().format("YYYY-MM-DD");
    this.targetMuscle = "";
    this.targetMuscleDropdown = null;
    this.equipment = "";
    this.equipmentDropdown = null;
    this.bodyWeight = 0;
    this.bodyFatPercentage = 0;
    this.workoutDuration = 0;
    // in minutes (strength)
    // Cardio-specific fields
    this.cardioSpeed = 0;
    // km/h
    this.cardioIncline = 0;
    // %
    this.cardioDuration = 0;
    // minutes
    // Dynamic section containers (set in onOpen)
    this.calorieContainer = null;
    this.inputsContainer = null;
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    const i18n = t();
    contentEl.createEl("h1", { text: i18n.modalTitle });
    this.bodyWeight = this.plugin.settings.bodyWeight;
    this.bodyFatPercentage = this.plugin.settings.bodyFatPercentage;
    this.renderExerciseSelect(contentEl);
    this.renderTargetMuscleSelect(contentEl);
    this.renderEquipmentSelect(contentEl);
    this.renderLogDatePicker(contentEl);
    this.calorieContainer = contentEl.createDiv();
    this.inputsContainer = contentEl.createDiv();
    this.refreshDynamicSections();
    this.renderButtons(contentEl);
  }
  isCardioMode() {
    return this.targetMuscle === "Cardio";
  }
  refreshDynamicSections() {
    if (!this.calorieContainer || !this.inputsContainer)
      return;
    this.calorieContainer.empty();
    this.inputsContainer.empty();
    if (this.plugin.settings.calculateCalories) {
      this.renderCalorieInputs(this.calorieContainer);
    }
    if (this.isCardioMode()) {
      this.renderCardioInputs(this.inputsContainer);
    } else {
      this.renderInputs(this.inputsContainer);
    }
  }
  renderCalorieInputs(containerEl) {
    const i18n = t();
    new import_obsidian3.Setting(containerEl).setName(i18n.bodyWeightLabel).setDesc(i18n.bodyWeightDesc).addText((text) => {
      text.inputEl.type = "number";
      text.setValue(this.bodyWeight.toString());
      text.onChange((value) => {
        this.bodyWeight = parseFloat(value) || 0;
      });
    });
    new import_obsidian3.Setting(containerEl).setName(i18n.bodyFatLabel).setDesc(i18n.bodyFatDesc).addText((text) => {
      text.inputEl.type = "number";
      text.setValue(this.bodyFatPercentage.toString());
      text.onChange((value) => {
        this.bodyFatPercentage = parseFloat(value) || 0;
      });
    });
    if (!this.isCardioMode()) {
      new import_obsidian3.Setting(containerEl).setName(i18n.workoutDurationLabel).setDesc(i18n.workoutDurationDesc).addText((text) => {
        text.inputEl.type = "number";
        text.setValue(this.workoutDuration.toString());
        text.onChange((value) => {
          this.workoutDuration = parseFloat(value) || 0;
        });
      });
    }
  }
  renderCardioInputs(containerEl) {
    const i18n = t();
    const card = containerEl.createDiv({ cls: "cardio-input-card" });
    card.createEl("p", { cls: "cardio-input-card__label", text: i18n.cardioSectionLabel });
    new import_obsidian3.Setting(card).setName(i18n.cardioSpeedLabel).addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.step = "0.1";
      text.setValue(this.cardioSpeed > 0 ? this.cardioSpeed.toString() : "");
      text.onChange((value) => {
        this.cardioSpeed = parseFloat(value) || 0;
      });
    });
    new import_obsidian3.Setting(card).setName(i18n.cardioInclineLabel).addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.step = "0.5";
      text.setValue(this.cardioIncline > 0 ? this.cardioIncline.toString() : "");
      text.onChange((value) => {
        this.cardioIncline = parseFloat(value) || 0;
      });
    });
    new import_obsidian3.Setting(card).setName(i18n.cardioDurationLabel).addText((text) => {
      text.inputEl.type = "number";
      text.setValue(this.cardioDuration > 0 ? this.cardioDuration.toString() : "");
      text.onChange((value) => {
        this.cardioDuration = parseFloat(value) || 0;
      });
    });
  }
  /**
   * Render the Select/Text field for exercise name
   */
  renderExerciseSelect(containerEl) {
    const i18n = t();
    new import_obsidian3.Setting(containerEl).setName(i18n.exerciseLabel).setDesc(i18n.exerciseDesc).addText((text) => {
      text.setPlaceholder(i18n.exercisePlaceholder);
      const dataListId = "exercises-list";
      let datalist = containerEl.querySelector(
        `#${dataListId}`
      );
      if (!datalist) {
        datalist = containerEl.createEl("datalist", {
          attr: { id: dataListId }
        });
      }
      const folderPath = this.plugin.settings.exerciseFolder;
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (folder instanceof import_obsidian3.TFolder) {
        folder.children.forEach((child) => {
          if (child.name.endsWith(".md")) {
            datalist.createEl("option", {
              value: child.name.replace(".md", "")
            });
          }
        });
      }
      text.inputEl.setAttribute("list", dataListId);
      text.onChange((value) => {
        this.exerciseName = value;
        const fileName = this.exerciseName.endsWith(".md") ? this.exerciseName : `${this.exerciseName}.md`;
        const filePath = `${this.plugin.settings.exerciseFolder}/${fileName}`;
        const file = this.app.vault.getAbstractFileByPath(filePath);
        if (file instanceof import_obsidian3.TFile) {
          const fileCache = this.app.metadataCache.getFileCache(file);
          const frontmatter = fileCache == null ? void 0 : fileCache.frontmatter;
          let muscleChanged = false;
          if (frontmatter && frontmatter.target_muscle) {
            const targetMuscle = Array.isArray(frontmatter.target_muscle) ? frontmatter.target_muscle[0] : frontmatter.target_muscle;
            if (targetMuscle && this.targetMuscleDropdown) {
              this.targetMuscle = targetMuscle;
              this.targetMuscleDropdown.setValue(targetMuscle);
              muscleChanged = true;
            }
          }
          if (frontmatter && frontmatter.equipment) {
            if (this.equipmentDropdown) {
              this.equipment = frontmatter.equipment;
              this.equipmentDropdown.setValue(frontmatter.equipment);
            }
          }
          if (muscleChanged) {
            this.refreshDynamicSections();
          }
        }
      });
    });
  }
  /**
   * Render the dropdown for target muscle
   */
  renderTargetMuscleSelect(containerEl) {
    const i18n = t();
    new import_obsidian3.Setting(containerEl).setName(i18n.targetMuscleLabel).setDesc(i18n.targetMuscleDesc).addDropdown((dropdown) => {
      this.targetMuscleDropdown = dropdown;
      TARGET_MUSCLES.forEach((muscle, idx) => {
        var _a;
        dropdown.addOption(muscle, (_a = i18n.targetMuscleOptions[idx]) != null ? _a : muscle);
      });
      dropdown.setValue(this.targetMuscle).onChange((value) => {
        this.targetMuscle = value;
        this.refreshDynamicSections();
      });
    });
  }
  /**
   * Render the dropdown for equipment type
   */
  renderEquipmentSelect(containerEl) {
    const i18n = t();
    new import_obsidian3.Setting(containerEl).setName(i18n.equipmentLabel).setDesc(i18n.equipmentDesc).addDropdown((dropdown) => {
      this.equipmentDropdown = dropdown;
      EQUIPMENT_TYPES.forEach((equipment, idx) => {
        var _a;
        dropdown.addOption(equipment, (_a = i18n.equipmentTypeOptions[idx]) != null ? _a : equipment);
      });
      dropdown.setValue(this.equipment).onChange((value) => {
        this.equipment = value;
        this.refreshDynamicSections();
      });
    });
  }
  /**
   * Render the date picker for the log
   */
  renderLogDatePicker(containerEl) {
    const i18n = t();
    new import_obsidian3.Setting(containerEl).setName(i18n.logDateLabel).setDesc(i18n.logDateDesc).addText((text) => {
      text.inputEl.type = "date";
      text.setValue(this.logDate).onChange((value) => {
        this.logDate = value;
      });
    });
  }
  /**
   * Render the weight, reps, and set type inputs
   */
  renderInputs(containerEl) {
    const i18n = t();
    const setsContainer = containerEl.createDiv({ cls: "sets-container" });
    const isBodyweight = () => this.equipment === "Bodyweight";
    const addSet = () => {
      const setIndex = this.sets.length;
      const setDiv = setsContainer.createDiv({ cls: "set-input-group" });
      if (!isBodyweight()) {
        new import_obsidian3.Setting(setDiv).setClass("set-input-block").setName(i18n.setWeight(setIndex + 1)).addText((text) => {
          text.inputEl.type = "number";
          text.onChange((value) => {
            this.sets[setIndex].weight = parseFloat(value) || 0;
          });
        });
      }
      new import_obsidian3.Setting(setDiv).setClass("set-input-block").setName(i18n.setReps(setIndex + 1)).addText((text) => {
        text.inputEl.type = "number";
        text.onChange((value) => {
          this.sets[setIndex].reps = parseInt(value, 10) || 0;
        });
      });
      new import_obsidian3.Setting(setDiv).setClass("set-input-block").setName(i18n.setRpe(setIndex + 1)).addDropdown((dropdown) => {
        dropdown.addOption("", "-");
        for (let rpe = 6; rpe <= 10; rpe += 0.5) {
          const val = rpe.toString();
          dropdown.addOption(val, val);
        }
        dropdown.setValue("").onChange((value) => {
          this.sets[setIndex].rpe = value ? parseFloat(value) : null;
        });
      });
      const removeButton = setDiv.createEl("button", { text: i18n.removeSet });
      removeButton.addEventListener("click", () => {
        this.sets.splice(setIndex, 1);
        setDiv.remove();
        this.updateSetLabels(setsContainer);
      });
      this.sets.push({ weight: isBodyweight() ? 1 : 0, reps: 0, rpe: null });
    };
    const addSetButton = containerEl.createEl("button", { text: i18n.addSet });
    addSetButton.addEventListener("click", addSet);
    this.sets = [];
    addSet();
  }
  /**
   * Update set labels after adding/removing sets
   */
  updateSetLabels(setsContainer) {
    const i18n = t();
    const isBodyweight = this.equipment === "Bodyweight";
    const setGroups = setsContainer.querySelectorAll(".set-input-group");
    setGroups.forEach((group, index) => {
      const items = group.querySelectorAll(".setting-item");
      if (isBodyweight) {
        if (items[0])
          items[0].querySelector(".setting-name").textContent = i18n.setReps(index + 1);
        if (items[1])
          items[1].querySelector(".setting-name").textContent = i18n.setRpe(index + 1);
      } else {
        if (items[0])
          items[0].querySelector(".setting-name").textContent = i18n.setWeight(index + 1);
        if (items[1])
          items[1].querySelector(".setting-name").textContent = i18n.setReps(index + 1);
        if (items[2])
          items[2].querySelector(".setting-name").textContent = i18n.setRpe(index + 1);
      }
    });
  }
  /**
   * Render log / cancel buttons
   */
  renderButtons(containerEl) {
    const i18n = t();
    const buttonContainer = containerEl.createDiv({
      cls: "modal-button-container"
    });
    const cancelButton = buttonContainer.createEl("button", { text: i18n.cancel });
    cancelButton.addEventListener("click", () => {
      this.close();
    });
    const submitButton = buttonContainer.createEl("button", {
      text: i18n.logSet,
      cls: "mod-cta"
    });
    submitButton.addEventListener("click", () => {
      void this.submit();
    });
  }
  async submit() {
    const i18n = t();
    if (!this.exerciseName) {
      new import_obsidian3.Notice(i18n.noticeNoExercise);
      return;
    }
    try {
      const file = await getOrCreateExerciseNote(
        this.app,
        this.plugin.settings.exerciseFolder,
        this.exerciseName,
        this.targetMuscle,
        this.equipment
      );
      if (this.isCardioMode()) {
        await this.submitCardio(file);
      } else {
        await this.submitStrength(file);
      }
      this.close();
    } catch (error) {
      console.error(error);
      new import_obsidian3.Notice(i18n.noticeFailed);
    }
  }
  async submitStrength(file) {
    const i18n = t();
    const validSets = this.sets.filter((s) => s.weight > 0 && s.reps > 0);
    if (validSets.length === 0) {
      new import_obsidian3.Notice(i18n.noticeNoValidSet);
      return;
    }
    let extraData;
    if (this.plugin.settings.calculateCalories) {
      this.plugin.settings.bodyWeight = this.bodyWeight || this.plugin.settings.bodyWeight;
      this.plugin.settings.bodyFatPercentage = this.bodyFatPercentage || this.plugin.settings.bodyFatPercentage;
      await this.plugin.saveSettings();
      const mets = EQUIPMENT_METS[this.equipment] || 5;
      const perSetDuration = this.workoutDuration / validSets.length;
      const perSetCalories = calculateCalories(
        mets,
        this.bodyWeight,
        perSetDuration / 60
      );
      extraData = {
        duration: Math.round(perSetDuration * 10) / 10,
        calories: perSetCalories
      };
    }
    await appendLog(this.app, file, validSets, this.logDate, extraData);
    if (this.plugin.settings.calculateCalories && this.plugin.settings.bodyMetricsNote && this.bodyWeight > 0) {
      await appendBodyMetrics(
        this.app,
        this.plugin.settings.bodyMetricsNote,
        this.logDate,
        this.bodyWeight,
        this.bodyFatPercentage
      );
    }
    const isBodyweight = this.equipment === "Bodyweight";
    const setsSummary = validSets.map((s) => isBodyweight ? `BW x ${s.reps}reps` : `${s.weight}kg x ${s.reps}reps`).join(", ");
    new import_obsidian3.Notice(i18n.noticeLoggedStrength(setsSummary, this.exerciseName));
  }
  async submitCardio(file) {
    const i18n = t();
    if (this.cardioDuration <= 0) {
      new import_obsidian3.Notice(i18n.noticeNoDuration);
      return;
    }
    const calories = calculateWalkingCalorie(
      this.bodyWeight || this.plugin.settings.bodyWeight,
      this.cardioSpeed,
      this.cardioIncline,
      this.cardioDuration
    );
    await appendCardioLog(
      this.app,
      file,
      this.logDate,
      this.cardioSpeed,
      this.cardioIncline,
      this.cardioDuration,
      Math.round(calories)
    );
    if (this.plugin.settings.calculateCalories && this.plugin.settings.bodyMetricsNote && this.bodyWeight > 0) {
      await appendBodyMetrics(
        this.app,
        this.plugin.settings.bodyMetricsNote,
        this.logDate,
        this.bodyWeight,
        this.bodyFatPercentage
      );
    }
    new import_obsidian3.Notice(
      i18n.noticeLoggedCardio(this.cardioDuration, Math.round(calories), this.exerciseName)
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/DashboardView.ts
var import_obsidian4 = require("obsidian");
var DASHBOARD_VIEW_TYPE = "workout-dashboard";
var CHART_WIDTH = 480;
var CHART_HEIGHT = 200;
var CHART_PAD = { top: 20, right: 20, bottom: 44, left: 52 };
var DashboardView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentPeriod = "30d";
    this.selectedExercise = "";
    this.exerciseNames = [];
    this.bodyMetricsData = [];
    this.exerciseData = [];
    this.caloriesData = [];
    this.plugin = plugin;
  }
  getViewType() {
    return DASHBOARD_VIEW_TYPE;
  }
  getDisplayText() {
    return "Workout Dashboard";
  }
  getIcon() {
    return "bar-chart-2";
  }
  async onOpen() {
    await this.loadAll();
    this.render();
  }
  onClose() {
    return Promise.resolve();
  }
  // ─── Data Loading ─────────────────────────────────────────────────────────
  async loadAll() {
    this.exerciseNames = this.loadExerciseNames();
    if (this.exerciseNames.length > 0 && !this.selectedExercise) {
      this.selectedExercise = this.exerciseNames[0];
    }
    this.bodyMetricsData = await this.loadBodyMetrics();
    if (this.selectedExercise) {
      this.exerciseData = await this.loadExerciseData(this.selectedExercise);
    }
    this.caloriesData = await this.loadAllCalories();
  }
  loadExerciseNames() {
    const folderPath = this.plugin.settings.exerciseFolder;
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!(folder instanceof import_obsidian4.TFolder))
      return [];
    return folder.children.filter((f) => f instanceof import_obsidian4.TFile && f.name.endsWith(".md")).map((f) => f.name.replace(".md", "")).sort();
  }
  async loadBodyMetrics() {
    const notePath = this.plugin.settings.bodyMetricsNote;
    if (!notePath)
      return [];
    const normalizedPath = (0, import_obsidian4.normalizePath)(
      notePath.endsWith(".md") ? notePath : `${notePath}.md`
    );
    const file = this.app.vault.getAbstractFileByPath(normalizedPath);
    if (!(file instanceof import_obsidian4.TFile))
      return [];
    const content = await this.app.vault.read(file);
    const results = [];
    const re = /\[date:: ([^\]]+)\].*\[body_weight:: ([^\]]+)\](?:.*\[body_fat_percentage:: ([^\]]+)\])?/;
    for (const line of content.split("\n")) {
      const m = re.exec(line);
      if (!m)
        continue;
      const bw = parseFloat(m[2]);
      if (isNaN(bw))
        continue;
      const bf = m[3] ? parseFloat(m[3]) : 0;
      results.push({
        date: m[1].trim(),
        bodyWeight: bw,
        bodyFatPercentage: isNaN(bf) ? 0 : bf
      });
    }
    return results.sort((a, b) => a.date.localeCompare(b.date));
  }
  async loadAllCalories() {
    var _a;
    const map = /* @__PURE__ */ new Map();
    for (const name of this.exerciseNames) {
      const entries = await this.loadExerciseData(name);
      for (const e of entries) {
        if (e.calories > 0) {
          map.set(e.date, ((_a = map.get(e.date)) != null ? _a : 0) + e.calories);
        }
      }
    }
    return Array.from(map.entries()).map(([date, value]) => ({ date, value })).sort((a, b) => a.date.localeCompare(b.date));
  }
  async loadExerciseData(exerciseName) {
    const folderPath = this.plugin.settings.exerciseFolder;
    const filePath = (0, import_obsidian4.normalizePath)(`${folderPath}/${exerciseName}.md`);
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!(file instanceof import_obsidian4.TFile))
      return [];
    const content = await this.app.vault.read(file);
    const results = [];
    const re = /\[date:: ([^\]]+)\].*\[weight:: ([^\]]+)\].*\[reps:: ([^\]]+)\].*\[volume:: ([^\]]+)\].*\[rm:: ([^\]]+)\]/;
    const caloriesRe = /\[calories:: ([^\]]+)\]/;
    for (const line of content.split("\n")) {
      const m = re.exec(line);
      if (!m)
        continue;
      const weight = parseFloat(m[2]);
      const reps = parseInt(m[3]);
      const volume = parseFloat(m[4]);
      const rm = parseFloat(m[5]);
      if (isNaN(weight) || isNaN(reps))
        continue;
      const cm = caloriesRe.exec(line);
      const calories = cm ? parseFloat(cm[1]) : 0;
      results.push({
        date: m[1].trim(),
        weight,
        reps,
        volume: isNaN(volume) ? 0 : volume,
        rm: isNaN(rm) ? 0 : rm,
        calories: isNaN(calories) ? 0 : calories
      });
    }
    return results.sort((a, b) => a.date.localeCompare(b.date));
  }
  // ─── Aggregation & Filtering ───────────────────────────────────────────────
  aggregateMax(entries, field) {
    var _a;
    const map = /* @__PURE__ */ new Map();
    for (const e of entries) {
      map.set(e.date, Math.max((_a = map.get(e.date)) != null ? _a : -Infinity, e[field]));
    }
    return Array.from(map.entries()).map(([date, value]) => ({ date, value })).sort((a, b) => a.date.localeCompare(b.date));
  }
  aggregateSum(entries, field) {
    var _a;
    const map = /* @__PURE__ */ new Map();
    for (const e of entries) {
      map.set(e.date, ((_a = map.get(e.date)) != null ? _a : 0) + e[field]);
    }
    return Array.from(map.entries()).map(([date, value]) => ({ date, value })).sort((a, b) => a.date.localeCompare(b.date));
  }
  filterByPeriod(points, period) {
    if (period === "all")
      return points;
    const days = period === "7d" ? 7 : period === "30d" ? 30 : 365;
    const cutoff = window.moment().subtract(days, "days").format("YYYY-MM-DD");
    return points.filter((p) => p.date >= cutoff);
  }
  // ─── Rendering ────────────────────────────────────────────────────────────
  render() {
    const root = this.containerEl.children[1];
    root.empty();
    root.addClass("wl-dashboard");
    const i18n = t();
    const header = root.createDiv({ cls: "wl-dashboard__header" });
    header.createEl("h2", { text: i18n.dashboardTitle });
    const refreshBtn = header.createEl("button", {
      cls: "wl-dashboard__refresh",
      text: i18n.dashboardRefresh
    });
    refreshBtn.addEventListener("click", () => {
      void this.loadAll().then(() => this.render());
    });
    this.renderPeriodTabs(root);
    this.renderBodyMetricsSection(root);
    this.renderCaloriesSection(root);
    this.renderExerciseSection(root);
  }
  renderPeriodTabs(container) {
    const i18n = t();
    const tabs = [
      { label: i18n.periodWeek, value: "7d" },
      { label: i18n.periodMonth, value: "30d" },
      { label: i18n.periodYear, value: "365d" },
      { label: i18n.periodAll, value: "all" }
    ];
    const tabBar = container.createDiv({ cls: "wl-dashboard__tabs" });
    for (const tab of tabs) {
      const btn = tabBar.createEl("button", {
        cls: "wl-dashboard__tab" + (this.currentPeriod === tab.value ? " is-active" : ""),
        text: tab.label
      });
      btn.addEventListener("click", () => {
        this.currentPeriod = tab.value;
        this.render();
      });
    }
  }
  renderBodyMetricsSection(container) {
    const i18n = t();
    const section = container.createDiv({ cls: "wl-dashboard__section" });
    section.createEl("h3", { text: i18n.sectionBodyMetrics });
    if (this.bodyMetricsData.length === 0) {
      section.createDiv({
        cls: "wl-dashboard__empty",
        text: i18n.bodyMetricsEmpty
      });
      return;
    }
    const weightPoints = this.filterByPeriod(
      this.bodyMetricsData.map((e) => ({ date: e.date, value: e.bodyWeight })),
      this.currentPeriod
    );
    const fatPoints = this.filterByPeriod(
      this.bodyMetricsData.filter((e) => e.bodyFatPercentage > 0).map((e) => ({ date: e.date, value: e.bodyFatPercentage })),
      this.currentPeriod
    );
    const chartsRow = section.createDiv({ cls: "wl-dashboard__charts" });
    this.renderLineChart(chartsRow, weightPoints, i18n.chartWeight, "#4a9eff", "kg");
    if (fatPoints.length > 0) {
      this.renderLineChart(chartsRow, fatPoints, i18n.chartBodyFat, "#ff6b6b", "%");
    }
  }
  renderCaloriesSection(container) {
    if (this.caloriesData.length === 0)
      return;
    const i18n = t();
    const section = container.createDiv({ cls: "wl-dashboard__section" });
    section.createEl("h3", { text: i18n.sectionCalories });
    const points = this.filterByPeriod(this.caloriesData, this.currentPeriod);
    const chartsRow = section.createDiv({ cls: "wl-dashboard__charts" });
    this.renderLineChart(chartsRow, points, i18n.chartCaloriesLabel, "#f59e0b", "kcal");
  }
  renderExerciseSection(container) {
    const i18n = t();
    const section = container.createDiv({ cls: "wl-dashboard__section" });
    const sectionHeader = section.createDiv({ cls: "wl-dashboard__section-header" });
    sectionHeader.createEl("h3", { text: i18n.sectionExercise });
    if (this.exerciseNames.length === 0) {
      section.createDiv({
        cls: "wl-dashboard__empty",
        text: i18n.exerciseEmpty
      });
      return;
    }
    const select = sectionHeader.createEl("select", {
      cls: "wl-dashboard__exercise-select"
    });
    for (const name of this.exerciseNames) {
      const opt = select.createEl("option", { value: name, text: name });
      if (name === this.selectedExercise)
        opt.selected = true;
    }
    const chartsArea = section.createDiv({ cls: "wl-dashboard__exercise-charts" });
    this.renderExerciseCharts(chartsArea);
    select.addEventListener("change", () => {
      this.selectedExercise = select.value;
      void this.loadExerciseData(this.selectedExercise).then((data) => {
        this.exerciseData = data;
        chartsArea.empty();
        this.renderExerciseCharts(chartsArea);
      });
    });
  }
  renderExerciseCharts(container) {
    const i18n = t();
    if (!this.selectedExercise || this.exerciseData.length === 0) {
      container.createDiv({
        cls: "wl-dashboard__empty",
        text: i18n.exerciseDataEmpty
      });
      return;
    }
    const rmPoints = this.filterByPeriod(
      this.aggregateMax(this.exerciseData, "rm"),
      this.currentPeriod
    );
    const volPoints = this.filterByPeriod(
      this.aggregateSum(this.exerciseData, "volume"),
      this.currentPeriod
    );
    const chartsRow = container.createDiv({ cls: "wl-dashboard__charts" });
    this.renderLineChart(chartsRow, rmPoints, i18n.chartEstimated1RM, "#a78bfa", "kg");
    this.renderLineChart(chartsRow, volPoints, i18n.chartTotalVolume, "#34d399", "kg");
  }
  // ─── SVG Line Chart ────────────────────────────────────────────────────────
  renderLineChart(container, points, label, color, yUnit) {
    const wrapper = container.createDiv({ cls: "wl-chart" });
    wrapper.createEl("p", { cls: "wl-chart__label", text: label });
    if (points.length === 0) {
      wrapper.createDiv({ cls: "wl-chart__empty", text: t().chartNoData });
      return;
    }
    const W = CHART_WIDTH;
    const H = CHART_HEIGHT;
    const P = CHART_PAD;
    const iW = W - P.left - P.right;
    const iH = H - P.top - P.bottom;
    const values = points.map((p) => p.value);
    const rawMin = Math.min(...values);
    const rawMax = Math.max(...values);
    const spread = rawMax - rawMin || 1;
    const yMin = rawMin - spread * 0.08;
    const yMax = rawMax + spread * 0.08;
    const n = points.length;
    const xOf = (i) => n === 1 ? iW / 2 : i / (n - 1) * iW;
    const yOf = (v) => iH - (v - yMin) / (yMax - yMin) * iH;
    const svg = this.svgEl(wrapper, "svg", {
      viewBox: `0 0 ${W} ${H}`,
      class: "wl-chart__svg"
    });
    const g = this.svgEl(svg, "g", {
      transform: `translate(${P.left},${P.top})`
    });
    const gridCount = 4;
    for (let i = 0; i <= gridCount; i++) {
      const y = i / gridCount * iH;
      this.svgEl(g, "line", {
        x1: "0",
        y1: y.toFixed(1),
        x2: String(iW),
        y2: y.toFixed(1),
        class: "wl-chart__grid"
      });
      const val = yMax - i / gridCount * (yMax - yMin);
      const t2 = this.svgEl(g, "text", {
        x: "-6",
        y: y.toFixed(1),
        class: "wl-chart__axis-text",
        "dominant-baseline": "middle",
        "text-anchor": "end"
      });
      t2.textContent = val.toFixed(1);
    }
    const yt = this.svgEl(g, "text", {
      x: "-38",
      y: (iH / 2).toFixed(1),
      class: "wl-chart__axis-unit",
      "text-anchor": "middle",
      transform: `rotate(-90,-38,${(iH / 2).toFixed(1)})`
    });
    yt.textContent = yUnit;
    this.svgEl(g, "line", {
      x1: "0",
      y1: "0",
      x2: "0",
      y2: String(iH),
      class: "wl-chart__axis"
    });
    this.svgEl(g, "line", {
      x1: "0",
      y1: String(iH),
      x2: String(iW),
      y2: String(iH),
      class: "wl-chart__axis"
    });
    const maxLabels = 6;
    const step = Math.max(1, Math.ceil(n / maxLabels));
    for (let i = 0; i < n; i += step) {
      const xt = this.svgEl(g, "text", {
        x: xOf(i).toFixed(1),
        y: (iH + 14).toFixed(1),
        class: "wl-chart__axis-text",
        "text-anchor": "middle"
      });
      xt.textContent = points[i].date.substring(5).replace("-", "/");
    }
    if (n > 1) {
      const areaD = `M${xOf(0).toFixed(1)},${iH} ` + points.map((p, i) => `L${xOf(i).toFixed(1)},${yOf(p.value).toFixed(1)}`).join(" ") + ` L${xOf(n - 1).toFixed(1)},${iH} Z`;
      this.svgEl(g, "path", {
        d: areaD,
        class: "wl-chart__area",
        fill: color
      });
    }
    if (n > 1) {
      const lineD = points.map((p, i) => `${i === 0 ? "M" : "L"}${xOf(i).toFixed(1)},${yOf(p.value).toFixed(1)}`).join(" ");
      this.svgEl(g, "path", {
        d: lineD,
        class: "wl-chart__line",
        stroke: color,
        fill: "none"
      });
    }
    for (let i = 0; i < n; i++) {
      const circle = this.svgEl(g, "circle", {
        cx: xOf(i).toFixed(1),
        cy: yOf(points[i].value).toFixed(1),
        r: "4",
        class: "wl-chart__dot",
        fill: color
      });
      const title = document.createElementNS("http://www.w3.org/2000/svg", "title");
      title.textContent = `${points[i].date}: ${points[i].value.toFixed(1)} ${yUnit}`;
      circle.appendChild(title);
    }
  }
  svgEl(parent, tag, attrs) {
    const el = document.createElementNS("http://www.w3.org/2000/svg", tag);
    for (const k in attrs) {
      el.setAttribute(k, attrs[k]);
    }
    parent.appendChild(el);
    return el;
  }
};

// src/main.ts
var WorkoutLoggerPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      DASHBOARD_VIEW_TYPE,
      (leaf) => new DashboardView(leaf, this)
    );
    const ribbonIconEl = this.addRibbonIcon(
      "bar-chart-2",
      "Workout dashboard",
      () => {
        this.activateDashboard();
      }
    );
    ribbonIconEl.addClass("workout-logger-ribbon-class");
    this.addCommand({
      id: "open-dashboard",
      name: "Open dashboard",
      callback: () => {
        this.activateDashboard();
      }
    });
    this.addCommand({
      id: "open-logger",
      name: "Open logger",
      callback: () => {
        new LoggerModal(this.app, this).open();
      }
    });
    this.addSettingTab(new WorkoutLoggerSettingTab(this.app, this));
  }
  onunload() {
  }
  async activateDashboard() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(DASHBOARD_VIEW_TYPE)[0];
    if (!leaf) {
      leaf = workspace.getLeaf(false);
      await leaf.setViewState({ type: DASHBOARD_VIEW_TYPE, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
